🤣Jeff broke this somehow. Probably a linter.
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 37: 'endblock'. Did you forget to register or load this tag?